const express = require("express");
const pages = require("../controller/htmlController");
const router = express.Router();
router.route("/").get(pages.index);
router.route("/task01").get(pages.task01);
// router.route("/index").get(pages.index);
router.route("/aboutus").get(pages.aboutUs);
router.route("/login").get(pages.login);
router.route("/signup").get(pages.signUp);
module.exports = router;
